### ISSUE TITLE
Build-trigger is successful even when the upstream is invalid

### ISSUE THREAD

**Issue by khermano** [jboss-set/build-trigger#13]
When picking the project to be build the build-trigger autofill the upstream, but after changing it somehow, e.g.: leave only `git`, the build-trigger successfuly send a message to the Datagrepper. Should we allow changing the upstream attribute if the data are taken from the database? And if yes, maybe some input validation would be nice, like if the `https://` is in the beginning or if it ends with `.git` when containing `git@`.

**Comment by petrberan** [comment]
> Should we allow changing the upstream attribute if the data are taken from the database?

Yes. There are projects with internal repos, those repos would not ideally be shared

**Comment by petrberan** [comment]
Obsolete
