### ISSUE TITLE
Cannot fetch info from github

### ISSUE THREAD

**Issue by petrberan** [jboss-set/build-trigger#47]
When deployed the application cannot fetch data from github.com and gets 403 as a response from `githubRestClient.getRefsInfo()` even while using correct credentials. Locally it works fine, Openshift terminal is also able to ping the api regardless of the key. Maybe Docker or pod settings?

**Comment by khermano** [comment]
It looks like the github-key was changed in OpenShift secrets, but the pod (currently only one running - created 3.10.2024) still has stored the previous one. I think we need to kill the currently running pod and create and run a new one with new secrets. Hopefully, I am making sense.
